/// <reference path="../../../../../node_modules/ts-bytearray/ts-bytearray.d.ts" />
import INetworkType = require('../../../network-type');
import { ICustomDataOutput, ICustomDataInput } from '../../../custom-data-wrapper';
import ObjectEffectInteger = require('../data/items/effects/object-effect-integer');
declare class MountClientData implements INetworkType {
    static ID: number;
    id: number;
    model: number;
    ancestor: number[];
    behaviors: number[];
    name: string;
    sex: boolean;
    ownerId: number;
    experience: number;
    experienceForLevel: number;
    experienceForNextLevel: number;
    level: number;
    isRideable: boolean;
    maxPods: number;
    isWild: boolean;
    stamina: number;
    staminaMax: number;
    maturity: number;
    maturityForAdult: number;
    energy: number;
    energyMax: number;
    serenity: number;
    aggressivityMax: number;
    serenityMax: number;
    love: number;
    loveMax: number;
    fecondationTime: number;
    isFecondationReady: boolean;
    boostLimiter: number;
    boostMax: number;
    reproductionCount: number;
    reproductionCountMax: number;
    effectList: ObjectEffectInteger[];
    constructor();
    getTypeId(): number;
    reset(): void;
    serialize(param1: ICustomDataOutput): void;
    serializeAs_MountClientData(param1: ICustomDataOutput): void;
    deserialize(param1: ICustomDataInput): void;
    deserializeAs_MountClientData(param1: ICustomDataInput): void;
}
export = MountClientData;
