import INetworkType = require('./network-type');

import StatisticData = require('./types/common/basic/statistic-data');
import StatisticDataBoolean = require('./types/common/basic/statistic-data-boolean');
import StatisticDataByte = require('./types/common/basic/statistic-data-byte');
import StatisticDataInt = require('./types/common/basic/statistic-data-int');
import StatisticDataShort = require('./types/common/basic/statistic-data-short');
import StatisticDataString = require('./types/common/basic/statistic-data-string');
import GameServerInformations = require('./types/connection/game-server-informations');
import Achievement = require('./types/game/achievement/achievement');
import AchievementObjective = require('./types/game/achievement/achievement-objective');
import AchievementRewardable = require('./types/game/achievement/achievement-rewardable');
import AchievementStartedObjective = require('./types/game/achievement/achievement-started-objective');
import FightDispellableEffectExtendedInformations = require('./types/game/action/fight/fight-dispellable-effect-extended-informations');
import AbstractFightDispellableEffect = require('./types/game/actions/fight/abstract-fight-dispellable-effect');
import FightTemporaryBoostEffect = require('./types/game/actions/fight/fight-temporary-boost-effect');
import FightTemporaryBoostStateEffect = require('./types/game/actions/fight/fight-temporary-boost-state-effect');
import FightTemporaryBoostWeaponDamagesEffect = require('./types/game/actions/fight/fight-temporary-boost-weapon-damages-effect');
import FightTemporarySpellBoostEffect = require('./types/game/actions/fight/fight-temporary-spell-boost-effect');
import FightTemporarySpellImmunityEffect = require('./types/game/actions/fight/fight-temporary-spell-immunity-effect');
import FightTriggeredEffect = require('./types/game/actions/fight/fight-triggered-effect');
import GameActionMark = require('./types/game/actions/fight/game-action-mark');
import GameActionMarkedCell = require('./types/game/actions/fight/game-action-marked-cell');
import ServerSessionConstant = require('./types/game/approach/server-session-constant');
import ServerSessionConstantInteger = require('./types/game/approach/server-session-constant-integer');
import ServerSessionConstantLong = require('./types/game/approach/server-session-constant-long');
import ServerSessionConstantString = require('./types/game/approach/server-session-constant-string');
import AbstractCharacterInformation = require('./types/game/character/abstract-character-information');
import CharacterMinimalAllianceInformations = require('./types/game/character/character-minimal-alliance-informations');
import CharacterMinimalGuildInformations = require('./types/game/character/character-minimal-guild-informations');
import CharacterMinimalInformations = require('./types/game/character/character-minimal-informations');
import CharacterMinimalPlusLookAndGradeInformations = require('./types/game/character/character-minimal-plus-look-and-grade-informations');
import CharacterMinimalPlusLookInformations = require('./types/game/character/character-minimal-plus-look-informations');
import ActorAlignmentInformations = require('./types/game/character/alignment/actor-alignment-informations');
import ActorExtendedAlignmentInformations = require('./types/game/character/alignment/actor-extended-alignment-informations');
import CharacterBaseCharacteristic = require('./types/game/character/characteristic/character-base-characteristic');
import CharacterCharacteristicsInformations = require('./types/game/character/characteristic/character-characteristics-informations');
import CharacterSpellModification = require('./types/game/character/characteristic/character-spell-modification');
import AbstractCharacterToRefurbishInformation = require('./types/game/character/choice/abstract-character-to-refurbish-information');
import CharacterBaseInformations = require('./types/game/character/choice/character-base-informations');
import CharacterHardcoreOrEpicInformations = require('./types/game/character/choice/character-hardcore-or-epic-informations');
import CharacterRemodelingInformation = require('./types/game/character/choice/character-remodeling-information');
import CharacterToRecolorInformation = require('./types/game/character/choice/character-to-recolor-information');
import CharacterToRelookInformation = require('./types/game/character/choice/character-to-relook-information');
import CharacterToRemodelInformations = require('./types/game/character/choice/character-to-remodel-informations');
import RemodelingInformation = require('./types/game/character/choice/remodeling-information');
import ActorRestrictionsInformations = require('./types/game/character/restriction/actor-restrictions-informations');
import PlayerStatus = require('./types/game/character/status/player-status');
import PlayerStatusExtended = require('./types/game/character/status/player-status-extended');
import ActorOrientation = require('./types/game/context/actor-orientation');
import EntityDispositionInformations = require('./types/game/context/entity-disposition-informations');
import EntityMovementInformations = require('./types/game/context/entity-movement-informations');
import FightEntityDispositionInformations = require('./types/game/context/fight-entity-disposition-informations');
import GameContextActorInformations = require('./types/game/context/game-context-actor-informations');
import GameRolePlayTaxCollectorInformations = require('./types/game/context/game-role-play-tax-collector-informations');
import IdentifiedEntityDispositionInformations = require('./types/game/context/identified-entity-disposition-informations');
import MapCoordinates = require('./types/game/context/map-coordinates');
import MapCoordinatesAndId = require('./types/game/context/map-coordinates-and-id');
import MapCoordinatesExtended = require('./types/game/context/map-coordinates-extended');
import TaxCollectorStaticExtendedInformations = require('./types/game/context/tax-collector-static-extended-informations');
import TaxCollectorStaticInformations = require('./types/game/context/tax-collector-static-informations');
import AbstractFightTeamInformations = require('./types/game/context/fight/abstract-fight-team-informations');
import FightAllianceTeamInformations = require('./types/game/context/fight/fight-alliance-team-informations');
import FightCommonInformations = require('./types/game/context/fight/fight-common-informations');
import FightExternalInformations = require('./types/game/context/fight/fight-external-informations');
import FightLoot = require('./types/game/context/fight/fight-loot');
import FightOptionsInformations = require('./types/game/context/fight/fight-options-informations');
import FightResultAdditionalData = require('./types/game/context/fight/fight-result-additional-data');
import FightResultExperienceData = require('./types/game/context/fight/fight-result-experience-data');
import FightResultFighterListEntry = require('./types/game/context/fight/fight-result-fighter-list-entry');
import FightResultListEntry = require('./types/game/context/fight/fight-result-list-entry');
import FightResultMutantListEntry = require('./types/game/context/fight/fight-result-mutant-list-entry');
import FightResultPlayerListEntry = require('./types/game/context/fight/fight-result-player-list-entry');
import FightResultPvpData = require('./types/game/context/fight/fight-result-pvp-data');
import FightResultTaxCollectorListEntry = require('./types/game/context/fight/fight-result-tax-collector-list-entry');
import FightTeamInformations = require('./types/game/context/fight/fight-team-informations');
import FightTeamLightInformations = require('./types/game/context/fight/fight-team-light-informations');
import FightTeamMemberCharacterInformations = require('./types/game/context/fight/fight-team-member-character-informations');
import FightTeamMemberCompanionInformations = require('./types/game/context/fight/fight-team-member-companion-informations');
import FightTeamMemberInformations = require('./types/game/context/fight/fight-team-member-informations');
import FightTeamMemberMonsterInformations = require('./types/game/context/fight/fight-team-member-monster-informations');
import FightTeamMemberTaxCollectorInformations = require('./types/game/context/fight/fight-team-member-tax-collector-informations');
import FightTeamMemberWithAllianceCharacterInformations = require('./types/game/context/fight/fight-team-member-with-alliance-character-informations');
import GameFightAIInformations = require('./types/game/context/fight/game-fight-a-i-informations');
import GameFightCharacterInformations = require('./types/game/context/fight/game-fight-character-informations');
import GameFightCompanionInformations = require('./types/game/context/fight/game-fight-companion-informations');
import GameFightFighterCompanionLightInformations = require('./types/game/context/fight/game-fight-fighter-companion-light-informations');
import GameFightFighterInformations = require('./types/game/context/fight/game-fight-fighter-informations');
import GameFightFighterLightInformations = require('./types/game/context/fight/game-fight-fighter-light-informations');
import GameFightFighterMonsterLightInformations = require('./types/game/context/fight/game-fight-fighter-monster-light-informations');
import GameFightFighterNamedInformations = require('./types/game/context/fight/game-fight-fighter-named-informations');
import GameFightFighterNamedLightInformations = require('./types/game/context/fight/game-fight-fighter-named-light-informations');
import GameFightFighterTaxCollectorLightInformations = require('./types/game/context/fight/game-fight-fighter-tax-collector-light-informations');
import GameFightMinimalStats = require('./types/game/context/fight/game-fight-minimal-stats');
import GameFightMinimalStatsPreparation = require('./types/game/context/fight/game-fight-minimal-stats-preparation');
import GameFightMonsterInformations = require('./types/game/context/fight/game-fight-monster-informations');
import GameFightMonsterWithAlignmentInformations = require('./types/game/context/fight/game-fight-monster-with-alignment-informations');
import GameFightMutantInformations = require('./types/game/context/fight/game-fight-mutant-informations');
import GameFightResumeSlaveInfo = require('./types/game/context/fight/game-fight-resume-slave-info');
import GameFightSpellCooldown = require('./types/game/context/fight/game-fight-spell-cooldown');
import GameFightTaxCollectorInformations = require('./types/game/context/fight/game-fight-tax-collector-informations');
import AllianceInformations = require('./types/game/context/roleplay/alliance-informations');
import AlternativeMonstersInGroupLightInformations = require('./types/game/context/roleplay/alternative-monsters-in-group-light-informations');
import AtlasPointsInformations = require('./types/game/context/roleplay/atlas-points-informations');
import BasicAllianceInformations = require('./types/game/context/roleplay/basic-alliance-informations');
import BasicGuildInformations = require('./types/game/context/roleplay/basic-guild-informations');
import BasicNamedAllianceInformations = require('./types/game/context/roleplay/basic-named-alliance-informations');
import GameRolePlayActorInformations = require('./types/game/context/roleplay/game-role-play-actor-informations');
import GameRolePlayCharacterInformations = require('./types/game/context/roleplay/game-role-play-character-informations');
import GameRolePlayGroupMonsterInformations = require('./types/game/context/roleplay/game-role-play-group-monster-informations');
import GameRolePlayGroupMonsterWaveInformations = require('./types/game/context/roleplay/game-role-play-group-monster-wave-informations');
import GameRolePlayHumanoidInformations = require('./types/game/context/roleplay/game-role-play-humanoid-informations');
import GameRolePlayMerchantInformations = require('./types/game/context/roleplay/game-role-play-merchant-informations');
import GameRolePlayMountInformations = require('./types/game/context/roleplay/game-role-play-mount-informations');
import GameRolePlayMutantInformations = require('./types/game/context/roleplay/game-role-play-mutant-informations');
import GameRolePlayNamedActorInformations = require('./types/game/context/roleplay/game-role-play-named-actor-informations');
import GameRolePlayNpcInformations = require('./types/game/context/roleplay/game-role-play-npc-informations');
import GameRolePlayNpcWithQuestInformations = require('./types/game/context/roleplay/game-role-play-npc-with-quest-informations');
import GameRolePlayPortalInformations = require('./types/game/context/roleplay/game-role-play-portal-informations');
import GameRolePlayPrismInformations = require('./types/game/context/roleplay/game-role-play-prism-informations');
import GameRolePlayTreasureHintInformations = require('./types/game/context/roleplay/game-role-play-treasure-hint-informations');
import GroupMonsterStaticInformations = require('./types/game/context/roleplay/group-monster-static-informations');
import GroupMonsterStaticInformationsWithAlternatives = require('./types/game/context/roleplay/group-monster-static-informations-with-alternatives');
import GuildInAllianceInformations = require('./types/game/context/roleplay/guild-in-alliance-informations');
import GuildInformations = require('./types/game/context/roleplay/guild-informations');
import HumanInformations = require('./types/game/context/roleplay/human-informations');
import HumanOption = require('./types/game/context/roleplay/human-option');
import HumanOptionAlliance = require('./types/game/context/roleplay/human-option-alliance');
import HumanOptionEmote = require('./types/game/context/roleplay/human-option-emote');
import HumanOptionFollowers = require('./types/game/context/roleplay/human-option-followers');
import HumanOptionGuild = require('./types/game/context/roleplay/human-option-guild');
import HumanOptionObjectUse = require('./types/game/context/roleplay/human-option-object-use');
import HumanOptionOrnament = require('./types/game/context/roleplay/human-option-ornament');
import HumanOptionTitle = require('./types/game/context/roleplay/human-option-title');
import MonsterInGroupInformations = require('./types/game/context/roleplay/monster-in-group-informations');
import MonsterInGroupLightInformations = require('./types/game/context/roleplay/monster-in-group-light-informations');
import ObjectItemInRolePlay = require('./types/game/context/roleplay/object-item-in-role-play');
import DecraftedItemStackInfo = require('./types/game/context/roleplay/job/decrafted-item-stack-info');
import JobCrafterDirectoryEntryJobInfo = require('./types/game/context/roleplay/job/job-crafter-directory-entry-job-info');
import JobCrafterDirectoryEntryPlayerInfo = require('./types/game/context/roleplay/job/job-crafter-directory-entry-player-info');
import JobCrafterDirectoryListEntry = require('./types/game/context/roleplay/job/job-crafter-directory-list-entry');
import JobCrafterDirectorySettings = require('./types/game/context/roleplay/job/job-crafter-directory-settings');
import JobDescription = require('./types/game/context/roleplay/job/job-description');
import JobExperience = require('./types/game/context/roleplay/job/job-experience');
import DungeonPartyFinderPlayer = require('./types/game/context/roleplay/party/dungeon-party-finder-player');
import NamedPartyTeam = require('./types/game/context/roleplay/party/named-party-team');
import NamedPartyTeamWithOutcome = require('./types/game/context/roleplay/party/named-party-team-with-outcome');
import PartyGuestInformations = require('./types/game/context/roleplay/party/party-guest-informations');
import PartyInvitationMemberInformations = require('./types/game/context/roleplay/party/party-invitation-member-informations');
import PartyMemberArenaInformations = require('./types/game/context/roleplay/party/party-member-arena-informations');
import PartyMemberGeoPosition = require('./types/game/context/roleplay/party/party-member-geo-position');
import PartyMemberInformations = require('./types/game/context/roleplay/party/party-member-informations');
import PartyCompanionBaseInformations = require('./types/game/context/roleplay/party/companion/party-companion-base-informations');
import PartyCompanionMemberInformations = require('./types/game/context/roleplay/party/companion/party-companion-member-informations');
import GameRolePlayNpcQuestFlag = require('./types/game/context/roleplay/quest/game-role-play-npc-quest-flag');
import QuestActiveDetailedInformations = require('./types/game/context/roleplay/quest/quest-active-detailed-informations');
import QuestActiveInformations = require('./types/game/context/roleplay/quest/quest-active-informations');
import QuestObjectiveInformations = require('./types/game/context/roleplay/quest/quest-objective-informations');
import QuestObjectiveInformationsWithCompletion = require('./types/game/context/roleplay/quest/quest-objective-informations-with-completion');
import PortalInformation = require('./types/game/context/roleplay/treasureHunt/portal-information');
import TreasureHuntFlag = require('./types/game/context/roleplay/treasureHunt/treasure-hunt-flag');
import TreasureHuntStep = require('./types/game/context/roleplay/treasureHunt/treasure-hunt-step');
import TreasureHuntStepDig = require('./types/game/context/roleplay/treasureHunt/treasure-hunt-step-dig');
import TreasureHuntStepFight = require('./types/game/context/roleplay/treasureHunt/treasure-hunt-step-fight');
import TreasureHuntStepFollowDirection = require('./types/game/context/roleplay/treasureHunt/treasure-hunt-step-follow-direction');
import TreasureHuntStepFollowDirectionToHint = require('./types/game/context/roleplay/treasureHunt/treasure-hunt-step-follow-direction-to-hint');
import TreasureHuntStepFollowDirectionToPOI = require('./types/game/context/roleplay/treasureHunt/treasure-hunt-step-follow-direction-to-p-o-i');
import BidExchangerObjectInfo = require('./types/game/data/items/bid-exchanger-object-info');
import GoldItem = require('./types/game/data/items/gold-item');
import Item = require('./types/game/data/items/item');
import ObjectItem = require('./types/game/data/items/object-item');
import ObjectItemGenericQuantity = require('./types/game/data/items/object-item-generic-quantity');
import ObjectItemInformationWithQuantity = require('./types/game/data/items/object-item-information-with-quantity');
import ObjectItemMinimalInformation = require('./types/game/data/items/object-item-minimal-information');
import ObjectItemNotInContainer = require('./types/game/data/items/object-item-not-in-container');
import ObjectItemQuantity = require('./types/game/data/items/object-item-quantity');
import ObjectItemToSell = require('./types/game/data/items/object-item-to-sell');
import ObjectItemToSellInBid = require('./types/game/data/items/object-item-to-sell-in-bid');
import ObjectItemToSellInHumanVendorShop = require('./types/game/data/items/object-item-to-sell-in-human-vendor-shop');
import ObjectItemToSellInNpcShop = require('./types/game/data/items/object-item-to-sell-in-npc-shop');
import SellerBuyerDescriptor = require('./types/game/data/items/seller-buyer-descriptor');
import SpellItem = require('./types/game/data/items/spell-item');
import ObjectEffect = require('./types/game/data/items/effects/object-effect');
import ObjectEffectCreature = require('./types/game/data/items/effects/object-effect-creature');
import ObjectEffectDate = require('./types/game/data/items/effects/object-effect-date');
import ObjectEffectDice = require('./types/game/data/items/effects/object-effect-dice');
import ObjectEffectDuration = require('./types/game/data/items/effects/object-effect-duration');
import ObjectEffectInteger = require('./types/game/data/items/effects/object-effect-integer');
import ObjectEffectLadder = require('./types/game/data/items/effects/object-effect-ladder');
import ObjectEffectMinMax = require('./types/game/data/items/effects/object-effect-min-max');
import ObjectEffectMount = require('./types/game/data/items/effects/object-effect-mount');
import ObjectEffectString = require('./types/game/data/items/effects/object-effect-string');
import ProtectedEntityWaitingForHelpInfo = require('./types/game/fight/protected-entity-waiting-for-help-info');
import AbstractContactInformations = require('./types/game/friend/abstract-contact-informations');
import FriendInformations = require('./types/game/friend/friend-informations');
import FriendOnlineInformations = require('./types/game/friend/friend-online-informations');
import FriendSpouseInformations = require('./types/game/friend/friend-spouse-informations');
import FriendSpouseOnlineInformations = require('./types/game/friend/friend-spouse-online-informations');
import IgnoredInformations = require('./types/game/friend/ignored-informations');
import IgnoredOnlineInformations = require('./types/game/friend/ignored-online-informations');
import GuildEmblem = require('./types/game/guild/guild-emblem');
import GuildMember = require('./types/game/guild/guild-member');
import AdditionalTaxCollectorInformations = require('./types/game/guild/tax/additional-tax-collector-informations');
import TaxCollectorBasicInformations = require('./types/game/guild/tax/tax-collector-basic-informations');
import TaxCollectorComplementaryInformations = require('./types/game/guild/tax/tax-collector-complementary-informations');
import TaxCollectorFightersInformation = require('./types/game/guild/tax/tax-collector-fighters-information');
import TaxCollectorGuildInformations = require('./types/game/guild/tax/tax-collector-guild-informations');
import TaxCollectorInformations = require('./types/game/guild/tax/tax-collector-informations');
import TaxCollectorLootInformations = require('./types/game/guild/tax/tax-collector-loot-informations');
import TaxCollectorWaitingForHelpInformations = require('./types/game/guild/tax/tax-collector-waiting-for-help-informations');
import AccountHouseInformations = require('./types/game/house/account-house-informations');
import HouseInformations = require('./types/game/house/house-informations');
import HouseInformationsExtended = require('./types/game/house/house-informations-extended');
import HouseInformationsForGuild = require('./types/game/house/house-informations-for-guild');
import HouseInformationsForSell = require('./types/game/house/house-informations-for-sell');
import HouseInformationsInside = require('./types/game/house/house-informations-inside');
import Idol = require('./types/game/idol/idol');
import PartyIdol = require('./types/game/idol/party-idol');
import InteractiveElement = require('./types/game/interactive/interactive-element');
import InteractiveElementNamedSkill = require('./types/game/interactive/interactive-element-named-skill');
import InteractiveElementSkill = require('./types/game/interactive/interactive-element-skill');
import InteractiveElementWithAgeBonus = require('./types/game/interactive/interactive-element-with-age-bonus');
import MapObstacle = require('./types/game/interactive/map-obstacle');
import StatedElement = require('./types/game/interactive/stated-element');
import SkillActionDescription = require('./types/game/interactive/skill/skill-action-description');
import SkillActionDescriptionCollect = require('./types/game/interactive/skill/skill-action-description-collect');
import SkillActionDescriptionCraft = require('./types/game/interactive/skill/skill-action-description-craft');
import SkillActionDescriptionTimed = require('./types/game/interactive/skill/skill-action-description-timed');
import IdolsPreset = require('./types/game/inventory/preset/idols-preset');
import Preset = require('./types/game/inventory/preset/preset');
import PresetItem = require('./types/game/inventory/preset/preset-item');
import EntityLook = require('./types/game/look/entity-look');
import IndexedEntityLook = require('./types/game/look/indexed-entity-look');
import SubEntity = require('./types/game/look/sub-entity');
import ItemDurability = require('./types/game/mount/item-durability');
import MountClientData = require('./types/game/mount/mount-client-data');
import UpdateMountBoost = require('./types/game/mount/update-mount-boost');
import UpdateMountIntBoost = require('./types/game/mount/update-mount-int-boost');
import MountInformationsForPaddock = require('./types/game/paddock/mount-informations-for-paddock');
import PaddockAbandonnedInformations = require('./types/game/paddock/paddock-abandonned-informations');
import PaddockBuyableInformations = require('./types/game/paddock/paddock-buyable-informations');
import PaddockContentInformations = require('./types/game/paddock/paddock-content-informations');
import PaddockInformations = require('./types/game/paddock/paddock-informations');
import PaddockInformationsForSell = require('./types/game/paddock/paddock-informations-for-sell');
import PaddockItem = require('./types/game/paddock/paddock-item');
import PaddockPrivateInformations = require('./types/game/paddock/paddock-private-informations');
import AllianceInsiderPrismInformation = require('./types/game/prism/alliance-insider-prism-information');
import AlliancePrismInformation = require('./types/game/prism/alliance-prism-information');
import PrismFightersInformation = require('./types/game/prism/prism-fighters-information');
import PrismGeolocalizedInformation = require('./types/game/prism/prism-geolocalized-information');
import PrismInformation = require('./types/game/prism/prism-information');
import PrismSubareaEmptyInfo = require('./types/game/prism/prism-subarea-empty-info');
import Shortcut = require('./types/game/shortcut/shortcut');
import ShortcutEmote = require('./types/game/shortcut/shortcut-emote');
import ShortcutObject = require('./types/game/shortcut/shortcut-object');
import ShortcutObjectIdolsPreset = require('./types/game/shortcut/shortcut-object-idols-preset');
import ShortcutObjectItem = require('./types/game/shortcut/shortcut-object-item');
import ShortcutObjectPreset = require('./types/game/shortcut/shortcut-object-preset');
import ShortcutSmiley = require('./types/game/shortcut/shortcut-smiley');
import ShortcutSpell = require('./types/game/shortcut/shortcut-spell');
import AbstractSocialGroupInfos = require('./types/game/social/abstract-social-group-infos');
import AllianceFactSheetInformations = require('./types/game/social/alliance-fact-sheet-informations');
import AllianceVersatileInformations = require('./types/game/social/alliance-versatile-informations');
import AlliancedGuildFactSheetInformations = require('./types/game/social/allianced-guild-fact-sheet-informations');
import GuildFactSheetInformations = require('./types/game/social/guild-fact-sheet-informations');
import GuildInAllianceVersatileInformations = require('./types/game/social/guild-in-alliance-versatile-informations');
import GuildInsiderFactSheetInformations = require('./types/game/social/guild-insider-fact-sheet-informations');
import GuildVersatileInformations = require('./types/game/social/guild-versatile-informations');
import StartupActionAddObject = require('./types/game/startup/startup-action-add-object');
import TrustCertificate = require('./types/secure/trust-certificate');
import ContentPart = require('./types/updater/content-part');
import Version = require('./types/version/version');
import VersionExtended = require('./types/version/version-extended');
import KrosmasterFigure = require('./types/web/krosmaster/krosmaster-figure');

class ProtocolTypeManager {
    private static _list: { [idx: number]: () => INetworkType };

    constructor() {
        ProtocolTypeManager._list = {};
        ProtocolTypeManager._list[StatisticData.ID] = () => { return new StatisticData(); };
        ProtocolTypeManager._list[StatisticDataBoolean.ID] = () => { return new StatisticDataBoolean(); };
        ProtocolTypeManager._list[StatisticDataByte.ID] = () => { return new StatisticDataByte(); };
        ProtocolTypeManager._list[StatisticDataInt.ID] = () => { return new StatisticDataInt(); };
        ProtocolTypeManager._list[StatisticDataShort.ID] = () => { return new StatisticDataShort(); };
        ProtocolTypeManager._list[StatisticDataString.ID] = () => { return new StatisticDataString(); };
        ProtocolTypeManager._list[GameServerInformations.ID] = () => { return new GameServerInformations(); };
        ProtocolTypeManager._list[Achievement.ID] = () => { return new Achievement(); };
        ProtocolTypeManager._list[AchievementObjective.ID] = () => { return new AchievementObjective(); };
        ProtocolTypeManager._list[AchievementRewardable.ID] = () => { return new AchievementRewardable(); };
        ProtocolTypeManager._list[AchievementStartedObjective.ID] = () => { return new AchievementStartedObjective(); };
        ProtocolTypeManager._list[FightDispellableEffectExtendedInformations.ID] = () => { return new FightDispellableEffectExtendedInformations(); };
        ProtocolTypeManager._list[AbstractFightDispellableEffect.ID] = () => { return new AbstractFightDispellableEffect(); };
        ProtocolTypeManager._list[FightTemporaryBoostEffect.ID] = () => { return new FightTemporaryBoostEffect(); };
        ProtocolTypeManager._list[FightTemporaryBoostStateEffect.ID] = () => { return new FightTemporaryBoostStateEffect(); };
        ProtocolTypeManager._list[FightTemporaryBoostWeaponDamagesEffect.ID] = () => { return new FightTemporaryBoostWeaponDamagesEffect(); };
        ProtocolTypeManager._list[FightTemporarySpellBoostEffect.ID] = () => { return new FightTemporarySpellBoostEffect(); };
        ProtocolTypeManager._list[FightTemporarySpellImmunityEffect.ID] = () => { return new FightTemporarySpellImmunityEffect(); };
        ProtocolTypeManager._list[FightTriggeredEffect.ID] = () => { return new FightTriggeredEffect(); };
        ProtocolTypeManager._list[GameActionMark.ID] = () => { return new GameActionMark(); };
        ProtocolTypeManager._list[GameActionMarkedCell.ID] = () => { return new GameActionMarkedCell(); };
        ProtocolTypeManager._list[ServerSessionConstant.ID] = () => { return new ServerSessionConstant(); };
        ProtocolTypeManager._list[ServerSessionConstantInteger.ID] = () => { return new ServerSessionConstantInteger(); };
        ProtocolTypeManager._list[ServerSessionConstantLong.ID] = () => { return new ServerSessionConstantLong(); };
        ProtocolTypeManager._list[ServerSessionConstantString.ID] = () => { return new ServerSessionConstantString(); };
        ProtocolTypeManager._list[AbstractCharacterInformation.ID] = () => { return new AbstractCharacterInformation(); };
        ProtocolTypeManager._list[CharacterMinimalAllianceInformations.ID] = () => { return new CharacterMinimalAllianceInformations(); };
        ProtocolTypeManager._list[CharacterMinimalGuildInformations.ID] = () => { return new CharacterMinimalGuildInformations(); };
        ProtocolTypeManager._list[CharacterMinimalInformations.ID] = () => { return new CharacterMinimalInformations(); };
        ProtocolTypeManager._list[CharacterMinimalPlusLookAndGradeInformations.ID] = () => { return new CharacterMinimalPlusLookAndGradeInformations(); };
        ProtocolTypeManager._list[CharacterMinimalPlusLookInformations.ID] = () => { return new CharacterMinimalPlusLookInformations(); };
        ProtocolTypeManager._list[ActorAlignmentInformations.ID] = () => { return new ActorAlignmentInformations(); };
        ProtocolTypeManager._list[ActorExtendedAlignmentInformations.ID] = () => { return new ActorExtendedAlignmentInformations(); };
        ProtocolTypeManager._list[CharacterBaseCharacteristic.ID] = () => { return new CharacterBaseCharacteristic(); };
        ProtocolTypeManager._list[CharacterCharacteristicsInformations.ID] = () => { return new CharacterCharacteristicsInformations(); };
        ProtocolTypeManager._list[CharacterSpellModification.ID] = () => { return new CharacterSpellModification(); };
        ProtocolTypeManager._list[AbstractCharacterToRefurbishInformation.ID] = () => { return new AbstractCharacterToRefurbishInformation(); };
        ProtocolTypeManager._list[CharacterBaseInformations.ID] = () => { return new CharacterBaseInformations(); };
        ProtocolTypeManager._list[CharacterHardcoreOrEpicInformations.ID] = () => { return new CharacterHardcoreOrEpicInformations(); };
        ProtocolTypeManager._list[CharacterRemodelingInformation.ID] = () => { return new CharacterRemodelingInformation(); };
        ProtocolTypeManager._list[CharacterToRecolorInformation.ID] = () => { return new CharacterToRecolorInformation(); };
        ProtocolTypeManager._list[CharacterToRelookInformation.ID] = () => { return new CharacterToRelookInformation(); };
        ProtocolTypeManager._list[CharacterToRemodelInformations.ID] = () => { return new CharacterToRemodelInformations(); };
        ProtocolTypeManager._list[RemodelingInformation.ID] = () => { return new RemodelingInformation(); };
        ProtocolTypeManager._list[ActorRestrictionsInformations.ID] = () => { return new ActorRestrictionsInformations(); };
        ProtocolTypeManager._list[PlayerStatus.ID] = () => { return new PlayerStatus(); };
        ProtocolTypeManager._list[PlayerStatusExtended.ID] = () => { return new PlayerStatusExtended(); };
        ProtocolTypeManager._list[ActorOrientation.ID] = () => { return new ActorOrientation(); };
        ProtocolTypeManager._list[EntityDispositionInformations.ID] = () => { return new EntityDispositionInformations(); };
        ProtocolTypeManager._list[EntityMovementInformations.ID] = () => { return new EntityMovementInformations(); };
        ProtocolTypeManager._list[FightEntityDispositionInformations.ID] = () => { return new FightEntityDispositionInformations(); };
        ProtocolTypeManager._list[GameContextActorInformations.ID] = () => { return new GameContextActorInformations(); };
        ProtocolTypeManager._list[GameRolePlayTaxCollectorInformations.ID] = () => { return new GameRolePlayTaxCollectorInformations(); };
        ProtocolTypeManager._list[IdentifiedEntityDispositionInformations.ID] = () => { return new IdentifiedEntityDispositionInformations(); };
        ProtocolTypeManager._list[MapCoordinates.ID] = () => { return new MapCoordinates(); };
        ProtocolTypeManager._list[MapCoordinatesAndId.ID] = () => { return new MapCoordinatesAndId(); };
        ProtocolTypeManager._list[MapCoordinatesExtended.ID] = () => { return new MapCoordinatesExtended(); };
        ProtocolTypeManager._list[TaxCollectorStaticExtendedInformations.ID] = () => { return new TaxCollectorStaticExtendedInformations(); };
        ProtocolTypeManager._list[TaxCollectorStaticInformations.ID] = () => { return new TaxCollectorStaticInformations(); };
        ProtocolTypeManager._list[AbstractFightTeamInformations.ID] = () => { return new AbstractFightTeamInformations(); };
        ProtocolTypeManager._list[FightAllianceTeamInformations.ID] = () => { return new FightAllianceTeamInformations(); };
        ProtocolTypeManager._list[FightCommonInformations.ID] = () => { return new FightCommonInformations(); };
        ProtocolTypeManager._list[FightExternalInformations.ID] = () => { return new FightExternalInformations(); };
        ProtocolTypeManager._list[FightLoot.ID] = () => { return new FightLoot(); };
        ProtocolTypeManager._list[FightOptionsInformations.ID] = () => { return new FightOptionsInformations(); };
        ProtocolTypeManager._list[FightResultAdditionalData.ID] = () => { return new FightResultAdditionalData(); };
        ProtocolTypeManager._list[FightResultExperienceData.ID] = () => { return new FightResultExperienceData(); };
        ProtocolTypeManager._list[FightResultFighterListEntry.ID] = () => { return new FightResultFighterListEntry(); };
        ProtocolTypeManager._list[FightResultListEntry.ID] = () => { return new FightResultListEntry(); };
        ProtocolTypeManager._list[FightResultMutantListEntry.ID] = () => { return new FightResultMutantListEntry(); };
        ProtocolTypeManager._list[FightResultPlayerListEntry.ID] = () => { return new FightResultPlayerListEntry(); };
        ProtocolTypeManager._list[FightResultPvpData.ID] = () => { return new FightResultPvpData(); };
        ProtocolTypeManager._list[FightResultTaxCollectorListEntry.ID] = () => { return new FightResultTaxCollectorListEntry(); };
        ProtocolTypeManager._list[FightTeamInformations.ID] = () => { return new FightTeamInformations(); };
        ProtocolTypeManager._list[FightTeamLightInformations.ID] = () => { return new FightTeamLightInformations(); };
        ProtocolTypeManager._list[FightTeamMemberCharacterInformations.ID] = () => { return new FightTeamMemberCharacterInformations(); };
        ProtocolTypeManager._list[FightTeamMemberCompanionInformations.ID] = () => { return new FightTeamMemberCompanionInformations(); };
        ProtocolTypeManager._list[FightTeamMemberInformations.ID] = () => { return new FightTeamMemberInformations(); };
        ProtocolTypeManager._list[FightTeamMemberMonsterInformations.ID] = () => { return new FightTeamMemberMonsterInformations(); };
        ProtocolTypeManager._list[FightTeamMemberTaxCollectorInformations.ID] = () => { return new FightTeamMemberTaxCollectorInformations(); };
        ProtocolTypeManager._list[FightTeamMemberWithAllianceCharacterInformations.ID] = () => { return new FightTeamMemberWithAllianceCharacterInformations(); };
        ProtocolTypeManager._list[GameFightAIInformations.ID] = () => { return new GameFightAIInformations(); };
        ProtocolTypeManager._list[GameFightCharacterInformations.ID] = () => { return new GameFightCharacterInformations(); };
        ProtocolTypeManager._list[GameFightCompanionInformations.ID] = () => { return new GameFightCompanionInformations(); };
        ProtocolTypeManager._list[GameFightFighterCompanionLightInformations.ID] = () => { return new GameFightFighterCompanionLightInformations(); };
        ProtocolTypeManager._list[GameFightFighterInformations.ID] = () => { return new GameFightFighterInformations(); };
        ProtocolTypeManager._list[GameFightFighterLightInformations.ID] = () => { return new GameFightFighterLightInformations(); };
        ProtocolTypeManager._list[GameFightFighterMonsterLightInformations.ID] = () => { return new GameFightFighterMonsterLightInformations(); };
        ProtocolTypeManager._list[GameFightFighterNamedInformations.ID] = () => { return new GameFightFighterNamedInformations(); };
        ProtocolTypeManager._list[GameFightFighterNamedLightInformations.ID] = () => { return new GameFightFighterNamedLightInformations(); };
        ProtocolTypeManager._list[GameFightFighterTaxCollectorLightInformations.ID] = () => { return new GameFightFighterTaxCollectorLightInformations(); };
        ProtocolTypeManager._list[GameFightMinimalStats.ID] = () => { return new GameFightMinimalStats(); };
        ProtocolTypeManager._list[GameFightMinimalStatsPreparation.ID] = () => { return new GameFightMinimalStatsPreparation(); };
        ProtocolTypeManager._list[GameFightMonsterInformations.ID] = () => { return new GameFightMonsterInformations(); };
        ProtocolTypeManager._list[GameFightMonsterWithAlignmentInformations.ID] = () => { return new GameFightMonsterWithAlignmentInformations(); };
        ProtocolTypeManager._list[GameFightMutantInformations.ID] = () => { return new GameFightMutantInformations(); };
        ProtocolTypeManager._list[GameFightResumeSlaveInfo.ID] = () => { return new GameFightResumeSlaveInfo(); };
        ProtocolTypeManager._list[GameFightSpellCooldown.ID] = () => { return new GameFightSpellCooldown(); };
        ProtocolTypeManager._list[GameFightTaxCollectorInformations.ID] = () => { return new GameFightTaxCollectorInformations(); };
        ProtocolTypeManager._list[AllianceInformations.ID] = () => { return new AllianceInformations(); };
        ProtocolTypeManager._list[AlternativeMonstersInGroupLightInformations.ID] = () => { return new AlternativeMonstersInGroupLightInformations(); };
        ProtocolTypeManager._list[AtlasPointsInformations.ID] = () => { return new AtlasPointsInformations(); };
        ProtocolTypeManager._list[BasicAllianceInformations.ID] = () => { return new BasicAllianceInformations(); };
        ProtocolTypeManager._list[BasicGuildInformations.ID] = () => { return new BasicGuildInformations(); };
        ProtocolTypeManager._list[BasicNamedAllianceInformations.ID] = () => { return new BasicNamedAllianceInformations(); };
        ProtocolTypeManager._list[GameRolePlayActorInformations.ID] = () => { return new GameRolePlayActorInformations(); };
        ProtocolTypeManager._list[GameRolePlayCharacterInformations.ID] = () => { return new GameRolePlayCharacterInformations(); };
        ProtocolTypeManager._list[GameRolePlayGroupMonsterInformations.ID] = () => { return new GameRolePlayGroupMonsterInformations(); };
        ProtocolTypeManager._list[GameRolePlayGroupMonsterWaveInformations.ID] = () => { return new GameRolePlayGroupMonsterWaveInformations(); };
        ProtocolTypeManager._list[GameRolePlayHumanoidInformations.ID] = () => { return new GameRolePlayHumanoidInformations(); };
        ProtocolTypeManager._list[GameRolePlayMerchantInformations.ID] = () => { return new GameRolePlayMerchantInformations(); };
        ProtocolTypeManager._list[GameRolePlayMountInformations.ID] = () => { return new GameRolePlayMountInformations(); };
        ProtocolTypeManager._list[GameRolePlayMutantInformations.ID] = () => { return new GameRolePlayMutantInformations(); };
        ProtocolTypeManager._list[GameRolePlayNamedActorInformations.ID] = () => { return new GameRolePlayNamedActorInformations(); };
        ProtocolTypeManager._list[GameRolePlayNpcInformations.ID] = () => { return new GameRolePlayNpcInformations(); };
        ProtocolTypeManager._list[GameRolePlayNpcWithQuestInformations.ID] = () => { return new GameRolePlayNpcWithQuestInformations(); };
        ProtocolTypeManager._list[GameRolePlayPortalInformations.ID] = () => { return new GameRolePlayPortalInformations(); };
        ProtocolTypeManager._list[GameRolePlayPrismInformations.ID] = () => { return new GameRolePlayPrismInformations(); };
        ProtocolTypeManager._list[GameRolePlayTreasureHintInformations.ID] = () => { return new GameRolePlayTreasureHintInformations(); };
        ProtocolTypeManager._list[GroupMonsterStaticInformations.ID] = () => { return new GroupMonsterStaticInformations(); };
        ProtocolTypeManager._list[GroupMonsterStaticInformationsWithAlternatives.ID] = () => { return new GroupMonsterStaticInformationsWithAlternatives(); };
        ProtocolTypeManager._list[GuildInAllianceInformations.ID] = () => { return new GuildInAllianceInformations(); };
        ProtocolTypeManager._list[GuildInformations.ID] = () => { return new GuildInformations(); };
        ProtocolTypeManager._list[HumanInformations.ID] = () => { return new HumanInformations(); };
        ProtocolTypeManager._list[HumanOption.ID] = () => { return new HumanOption(); };
        ProtocolTypeManager._list[HumanOptionAlliance.ID] = () => { return new HumanOptionAlliance(); };
        ProtocolTypeManager._list[HumanOptionEmote.ID] = () => { return new HumanOptionEmote(); };
        ProtocolTypeManager._list[HumanOptionFollowers.ID] = () => { return new HumanOptionFollowers(); };
        ProtocolTypeManager._list[HumanOptionGuild.ID] = () => { return new HumanOptionGuild(); };
        ProtocolTypeManager._list[HumanOptionObjectUse.ID] = () => { return new HumanOptionObjectUse(); };
        ProtocolTypeManager._list[HumanOptionOrnament.ID] = () => { return new HumanOptionOrnament(); };
        ProtocolTypeManager._list[HumanOptionTitle.ID] = () => { return new HumanOptionTitle(); };
        ProtocolTypeManager._list[MonsterInGroupInformations.ID] = () => { return new MonsterInGroupInformations(); };
        ProtocolTypeManager._list[MonsterInGroupLightInformations.ID] = () => { return new MonsterInGroupLightInformations(); };
        ProtocolTypeManager._list[ObjectItemInRolePlay.ID] = () => { return new ObjectItemInRolePlay(); };
        ProtocolTypeManager._list[DecraftedItemStackInfo.ID] = () => { return new DecraftedItemStackInfo(); };
        ProtocolTypeManager._list[JobCrafterDirectoryEntryJobInfo.ID] = () => { return new JobCrafterDirectoryEntryJobInfo(); };
        ProtocolTypeManager._list[JobCrafterDirectoryEntryPlayerInfo.ID] = () => { return new JobCrafterDirectoryEntryPlayerInfo(); };
        ProtocolTypeManager._list[JobCrafterDirectoryListEntry.ID] = () => { return new JobCrafterDirectoryListEntry(); };
        ProtocolTypeManager._list[JobCrafterDirectorySettings.ID] = () => { return new JobCrafterDirectorySettings(); };
        ProtocolTypeManager._list[JobDescription.ID] = () => { return new JobDescription(); };
        ProtocolTypeManager._list[JobExperience.ID] = () => { return new JobExperience(); };
        ProtocolTypeManager._list[DungeonPartyFinderPlayer.ID] = () => { return new DungeonPartyFinderPlayer(); };
        ProtocolTypeManager._list[NamedPartyTeam.ID] = () => { return new NamedPartyTeam(); };
        ProtocolTypeManager._list[NamedPartyTeamWithOutcome.ID] = () => { return new NamedPartyTeamWithOutcome(); };
        ProtocolTypeManager._list[PartyGuestInformations.ID] = () => { return new PartyGuestInformations(); };
        ProtocolTypeManager._list[PartyInvitationMemberInformations.ID] = () => { return new PartyInvitationMemberInformations(); };
        ProtocolTypeManager._list[PartyMemberArenaInformations.ID] = () => { return new PartyMemberArenaInformations(); };
        ProtocolTypeManager._list[PartyMemberGeoPosition.ID] = () => { return new PartyMemberGeoPosition(); };
        ProtocolTypeManager._list[PartyMemberInformations.ID] = () => { return new PartyMemberInformations(); };
        ProtocolTypeManager._list[PartyCompanionBaseInformations.ID] = () => { return new PartyCompanionBaseInformations(); };
        ProtocolTypeManager._list[PartyCompanionMemberInformations.ID] = () => { return new PartyCompanionMemberInformations(); };
        ProtocolTypeManager._list[GameRolePlayNpcQuestFlag.ID] = () => { return new GameRolePlayNpcQuestFlag(); };
        ProtocolTypeManager._list[QuestActiveDetailedInformations.ID] = () => { return new QuestActiveDetailedInformations(); };
        ProtocolTypeManager._list[QuestActiveInformations.ID] = () => { return new QuestActiveInformations(); };
        ProtocolTypeManager._list[QuestObjectiveInformations.ID] = () => { return new QuestObjectiveInformations(); };
        ProtocolTypeManager._list[QuestObjectiveInformationsWithCompletion.ID] = () => { return new QuestObjectiveInformationsWithCompletion(); };
        ProtocolTypeManager._list[PortalInformation.ID] = () => { return new PortalInformation(); };
        ProtocolTypeManager._list[TreasureHuntFlag.ID] = () => { return new TreasureHuntFlag(); };
        ProtocolTypeManager._list[TreasureHuntStep.ID] = () => { return new TreasureHuntStep(); };
        ProtocolTypeManager._list[TreasureHuntStepDig.ID] = () => { return new TreasureHuntStepDig(); };
        ProtocolTypeManager._list[TreasureHuntStepFight.ID] = () => { return new TreasureHuntStepFight(); };
        ProtocolTypeManager._list[TreasureHuntStepFollowDirection.ID] = () => { return new TreasureHuntStepFollowDirection(); };
        ProtocolTypeManager._list[TreasureHuntStepFollowDirectionToHint.ID] = () => { return new TreasureHuntStepFollowDirectionToHint(); };
        ProtocolTypeManager._list[TreasureHuntStepFollowDirectionToPOI.ID] = () => { return new TreasureHuntStepFollowDirectionToPOI(); };
        ProtocolTypeManager._list[BidExchangerObjectInfo.ID] = () => { return new BidExchangerObjectInfo(); };
        ProtocolTypeManager._list[GoldItem.ID] = () => { return new GoldItem(); };
        ProtocolTypeManager._list[Item.ID] = () => { return new Item(); };
        ProtocolTypeManager._list[ObjectItem.ID] = () => { return new ObjectItem(); };
        ProtocolTypeManager._list[ObjectItemGenericQuantity.ID] = () => { return new ObjectItemGenericQuantity(); };
        ProtocolTypeManager._list[ObjectItemInformationWithQuantity.ID] = () => { return new ObjectItemInformationWithQuantity(); };
        ProtocolTypeManager._list[ObjectItemMinimalInformation.ID] = () => { return new ObjectItemMinimalInformation(); };
        ProtocolTypeManager._list[ObjectItemNotInContainer.ID] = () => { return new ObjectItemNotInContainer(); };
        ProtocolTypeManager._list[ObjectItemQuantity.ID] = () => { return new ObjectItemQuantity(); };
        ProtocolTypeManager._list[ObjectItemToSell.ID] = () => { return new ObjectItemToSell(); };
        ProtocolTypeManager._list[ObjectItemToSellInBid.ID] = () => { return new ObjectItemToSellInBid(); };
        ProtocolTypeManager._list[ObjectItemToSellInHumanVendorShop.ID] = () => { return new ObjectItemToSellInHumanVendorShop(); };
        ProtocolTypeManager._list[ObjectItemToSellInNpcShop.ID] = () => { return new ObjectItemToSellInNpcShop(); };
        ProtocolTypeManager._list[SellerBuyerDescriptor.ID] = () => { return new SellerBuyerDescriptor(); };
        ProtocolTypeManager._list[SpellItem.ID] = () => { return new SpellItem(); };
        ProtocolTypeManager._list[ObjectEffect.ID] = () => { return new ObjectEffect(); };
        ProtocolTypeManager._list[ObjectEffectCreature.ID] = () => { return new ObjectEffectCreature(); };
        ProtocolTypeManager._list[ObjectEffectDate.ID] = () => { return new ObjectEffectDate(); };
        ProtocolTypeManager._list[ObjectEffectDice.ID] = () => { return new ObjectEffectDice(); };
        ProtocolTypeManager._list[ObjectEffectDuration.ID] = () => { return new ObjectEffectDuration(); };
        ProtocolTypeManager._list[ObjectEffectInteger.ID] = () => { return new ObjectEffectInteger(); };
        ProtocolTypeManager._list[ObjectEffectLadder.ID] = () => { return new ObjectEffectLadder(); };
        ProtocolTypeManager._list[ObjectEffectMinMax.ID] = () => { return new ObjectEffectMinMax(); };
        ProtocolTypeManager._list[ObjectEffectMount.ID] = () => { return new ObjectEffectMount(); };
        ProtocolTypeManager._list[ObjectEffectString.ID] = () => { return new ObjectEffectString(); };
        ProtocolTypeManager._list[ProtectedEntityWaitingForHelpInfo.ID] = () => { return new ProtectedEntityWaitingForHelpInfo(); };
        ProtocolTypeManager._list[AbstractContactInformations.ID] = () => { return new AbstractContactInformations(); };
        ProtocolTypeManager._list[FriendInformations.ID] = () => { return new FriendInformations(); };
        ProtocolTypeManager._list[FriendOnlineInformations.ID] = () => { return new FriendOnlineInformations(); };
        ProtocolTypeManager._list[FriendSpouseInformations.ID] = () => { return new FriendSpouseInformations(); };
        ProtocolTypeManager._list[FriendSpouseOnlineInformations.ID] = () => { return new FriendSpouseOnlineInformations(); };
        ProtocolTypeManager._list[IgnoredInformations.ID] = () => { return new IgnoredInformations(); };
        ProtocolTypeManager._list[IgnoredOnlineInformations.ID] = () => { return new IgnoredOnlineInformations(); };
        ProtocolTypeManager._list[GuildEmblem.ID] = () => { return new GuildEmblem(); };
        ProtocolTypeManager._list[GuildMember.ID] = () => { return new GuildMember(); };
        ProtocolTypeManager._list[AdditionalTaxCollectorInformations.ID] = () => { return new AdditionalTaxCollectorInformations(); };
        ProtocolTypeManager._list[TaxCollectorBasicInformations.ID] = () => { return new TaxCollectorBasicInformations(); };
        ProtocolTypeManager._list[TaxCollectorComplementaryInformations.ID] = () => { return new TaxCollectorComplementaryInformations(); };
        ProtocolTypeManager._list[TaxCollectorFightersInformation.ID] = () => { return new TaxCollectorFightersInformation(); };
        ProtocolTypeManager._list[TaxCollectorGuildInformations.ID] = () => { return new TaxCollectorGuildInformations(); };
        ProtocolTypeManager._list[TaxCollectorInformations.ID] = () => { return new TaxCollectorInformations(); };
        ProtocolTypeManager._list[TaxCollectorLootInformations.ID] = () => { return new TaxCollectorLootInformations(); };
        ProtocolTypeManager._list[TaxCollectorWaitingForHelpInformations.ID] = () => { return new TaxCollectorWaitingForHelpInformations(); };
        ProtocolTypeManager._list[AccountHouseInformations.ID] = () => { return new AccountHouseInformations(); };
        ProtocolTypeManager._list[HouseInformations.ID] = () => { return new HouseInformations(); };
        ProtocolTypeManager._list[HouseInformationsExtended.ID] = () => { return new HouseInformationsExtended(); };
        ProtocolTypeManager._list[HouseInformationsForGuild.ID] = () => { return new HouseInformationsForGuild(); };
        ProtocolTypeManager._list[HouseInformationsForSell.ID] = () => { return new HouseInformationsForSell(); };
        ProtocolTypeManager._list[HouseInformationsInside.ID] = () => { return new HouseInformationsInside(); };
        ProtocolTypeManager._list[Idol.ID] = () => { return new Idol(); };
        ProtocolTypeManager._list[PartyIdol.ID] = () => { return new PartyIdol(); };
        ProtocolTypeManager._list[InteractiveElement.ID] = () => { return new InteractiveElement(); };
        ProtocolTypeManager._list[InteractiveElementNamedSkill.ID] = () => { return new InteractiveElementNamedSkill(); };
        ProtocolTypeManager._list[InteractiveElementSkill.ID] = () => { return new InteractiveElementSkill(); };
        ProtocolTypeManager._list[InteractiveElementWithAgeBonus.ID] = () => { return new InteractiveElementWithAgeBonus(); };
        ProtocolTypeManager._list[MapObstacle.ID] = () => { return new MapObstacle(); };
        ProtocolTypeManager._list[StatedElement.ID] = () => { return new StatedElement(); };
        ProtocolTypeManager._list[SkillActionDescription.ID] = () => { return new SkillActionDescription(); };
        ProtocolTypeManager._list[SkillActionDescriptionCollect.ID] = () => { return new SkillActionDescriptionCollect(); };
        ProtocolTypeManager._list[SkillActionDescriptionCraft.ID] = () => { return new SkillActionDescriptionCraft(); };
        ProtocolTypeManager._list[SkillActionDescriptionTimed.ID] = () => { return new SkillActionDescriptionTimed(); };
        ProtocolTypeManager._list[IdolsPreset.ID] = () => { return new IdolsPreset(); };
        ProtocolTypeManager._list[Preset.ID] = () => { return new Preset(); };
        ProtocolTypeManager._list[PresetItem.ID] = () => { return new PresetItem(); };
        ProtocolTypeManager._list[EntityLook.ID] = () => { return new EntityLook(); };
        ProtocolTypeManager._list[IndexedEntityLook.ID] = () => { return new IndexedEntityLook(); };
        ProtocolTypeManager._list[SubEntity.ID] = () => { return new SubEntity(); };
        ProtocolTypeManager._list[ItemDurability.ID] = () => { return new ItemDurability(); };
        ProtocolTypeManager._list[MountClientData.ID] = () => { return new MountClientData(); };
        ProtocolTypeManager._list[UpdateMountBoost.ID] = () => { return new UpdateMountBoost(); };
        ProtocolTypeManager._list[UpdateMountIntBoost.ID] = () => { return new UpdateMountIntBoost(); };
        ProtocolTypeManager._list[MountInformationsForPaddock.ID] = () => { return new MountInformationsForPaddock(); };
        ProtocolTypeManager._list[PaddockAbandonnedInformations.ID] = () => { return new PaddockAbandonnedInformations(); };
        ProtocolTypeManager._list[PaddockBuyableInformations.ID] = () => { return new PaddockBuyableInformations(); };
        ProtocolTypeManager._list[PaddockContentInformations.ID] = () => { return new PaddockContentInformations(); };
        ProtocolTypeManager._list[PaddockInformations.ID] = () => { return new PaddockInformations(); };
        ProtocolTypeManager._list[PaddockInformationsForSell.ID] = () => { return new PaddockInformationsForSell(); };
        ProtocolTypeManager._list[PaddockItem.ID] = () => { return new PaddockItem(); };
        ProtocolTypeManager._list[PaddockPrivateInformations.ID] = () => { return new PaddockPrivateInformations(); };
        ProtocolTypeManager._list[AllianceInsiderPrismInformation.ID] = () => { return new AllianceInsiderPrismInformation(); };
        ProtocolTypeManager._list[AlliancePrismInformation.ID] = () => { return new AlliancePrismInformation(); };
        ProtocolTypeManager._list[PrismFightersInformation.ID] = () => { return new PrismFightersInformation(); };
        ProtocolTypeManager._list[PrismGeolocalizedInformation.ID] = () => { return new PrismGeolocalizedInformation(); };
        ProtocolTypeManager._list[PrismInformation.ID] = () => { return new PrismInformation(); };
        ProtocolTypeManager._list[PrismSubareaEmptyInfo.ID] = () => { return new PrismSubareaEmptyInfo(); };
        ProtocolTypeManager._list[Shortcut.ID] = () => { return new Shortcut(); };
        ProtocolTypeManager._list[ShortcutEmote.ID] = () => { return new ShortcutEmote(); };
        ProtocolTypeManager._list[ShortcutObject.ID] = () => { return new ShortcutObject(); };
        ProtocolTypeManager._list[ShortcutObjectIdolsPreset.ID] = () => { return new ShortcutObjectIdolsPreset(); };
        ProtocolTypeManager._list[ShortcutObjectItem.ID] = () => { return new ShortcutObjectItem(); };
        ProtocolTypeManager._list[ShortcutObjectPreset.ID] = () => { return new ShortcutObjectPreset(); };
        ProtocolTypeManager._list[ShortcutSmiley.ID] = () => { return new ShortcutSmiley(); };
        ProtocolTypeManager._list[ShortcutSpell.ID] = () => { return new ShortcutSpell(); };
        ProtocolTypeManager._list[AbstractSocialGroupInfos.ID] = () => { return new AbstractSocialGroupInfos(); };
        ProtocolTypeManager._list[AllianceFactSheetInformations.ID] = () => { return new AllianceFactSheetInformations(); };
        ProtocolTypeManager._list[AllianceVersatileInformations.ID] = () => { return new AllianceVersatileInformations(); };
        ProtocolTypeManager._list[AlliancedGuildFactSheetInformations.ID] = () => { return new AlliancedGuildFactSheetInformations(); };
        ProtocolTypeManager._list[GuildFactSheetInformations.ID] = () => { return new GuildFactSheetInformations(); };
        ProtocolTypeManager._list[GuildInAllianceVersatileInformations.ID] = () => { return new GuildInAllianceVersatileInformations(); };
        ProtocolTypeManager._list[GuildInsiderFactSheetInformations.ID] = () => { return new GuildInsiderFactSheetInformations(); };
        ProtocolTypeManager._list[GuildVersatileInformations.ID] = () => { return new GuildVersatileInformations(); };
        ProtocolTypeManager._list[StartupActionAddObject.ID] = () => { return new StartupActionAddObject(); };
        ProtocolTypeManager._list[TrustCertificate.ID] = () => { return new TrustCertificate(); };
        ProtocolTypeManager._list[ContentPart.ID] = () => { return new ContentPart(); };
        ProtocolTypeManager._list[Version.ID] = () => { return new Version(); };
        ProtocolTypeManager._list[VersionExtended.ID] = () => { return new VersionExtended(); };
        ProtocolTypeManager._list[KrosmasterFigure.ID] = () => { return new KrosmasterFigure(); };
    }

    public static getInstance(networkType: any, param2: number): INetworkType {
        let _loc3_ = ProtocolTypeManager._list[param2];
        if (!_loc3_) {
            throw new Error('Type with id ' + param2 + ' is unknown.');
        }
        return _loc3_();
    }
}

export = ProtocolTypeManager;
