var BreedEnum;
(function (BreedEnum) {
    BreedEnum[BreedEnum["UNDEFINED"] = 0] = "UNDEFINED";
    BreedEnum[BreedEnum["Feca"] = 1] = "Feca";
    BreedEnum[BreedEnum["Osamodas"] = 2] = "Osamodas";
    BreedEnum[BreedEnum["Enutrof"] = 3] = "Enutrof";
    BreedEnum[BreedEnum["Sram"] = 4] = "Sram";
    BreedEnum[BreedEnum["Xelor"] = 5] = "Xelor";
    BreedEnum[BreedEnum["Ecaflip"] = 6] = "Ecaflip";
    BreedEnum[BreedEnum["Eniripsa"] = 7] = "Eniripsa";
    BreedEnum[BreedEnum["Iop"] = 8] = "Iop";
    BreedEnum[BreedEnum["Cra"] = 9] = "Cra";
    BreedEnum[BreedEnum["Sadida"] = 10] = "Sadida";
    BreedEnum[BreedEnum["Sacrieur"] = 11] = "Sacrieur";
    BreedEnum[BreedEnum["Pandawa"] = 12] = "Pandawa";
    BreedEnum[BreedEnum["Roublard"] = 13] = "Roublard";
    BreedEnum[BreedEnum["Zobal"] = 14] = "Zobal";
    BreedEnum[BreedEnum["Steamer"] = 15] = "Steamer";
    BreedEnum[BreedEnum["Eliotrope"] = 16] = "Eliotrope";
    BreedEnum[BreedEnum["SUMMONED"] = -1] = "SUMMONED";
    BreedEnum[BreedEnum["MONSTER"] = -2] = "MONSTER";
    BreedEnum[BreedEnum["MONSTER_GROUP"] = -3] = "MONSTER_GROUP";
    BreedEnum[BreedEnum["NPC"] = -4] = "NPC";
    BreedEnum[BreedEnum["HUMAN_VENDOR"] = -5] = "HUMAN_VENDOR";
    BreedEnum[BreedEnum["TAX_COLLECTOR"] = -6] = "TAX_COLLECTOR";
    BreedEnum[BreedEnum["MUTANT"] = -7] = "MUTANT";
    BreedEnum[BreedEnum["MUTANT_IN_DUNGEON"] = -8] = "MUTANT_IN_DUNGEON";
    BreedEnum[BreedEnum["MOUNT_OUTSIDE"] = -9] = "MOUNT_OUTSIDE";
    BreedEnum[BreedEnum["PRISM"] = -10] = "PRISM";
    BreedEnum[BreedEnum["INCARNATION"] = -11] = "INCARNATION";
})(BreedEnum || (BreedEnum = {}));
module.exports = BreedEnum;
